# -*- coding: utf-8 -*-
"""primeiro exemplo em Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yto0xL5Sk0uTe7_lBWhwxfoJefyGdSte
"""

import pandas as pd

combustiveis_df = pd.read_excel ("ca-2021-02.xlsx")

# Usa o print para ver o dataframe!
print(combustiveis_df)

display(combustiveis_df)

#Exibe as primeiras 5 linhas
display(combustiveis_df.head())

# Quero, na verdade, exibir as primeiras 15 linhas
display(combustiveis_df.head(15))

print(combustiveis_df.shape)

print(combustiveis_df.shape[0])

#Quais são as colunas e que tipo de dados cada um tem...

print(combustiveis_df.info())

print(combustiveis_df.describe())

display(combustiveis_df['Revenda'])

#add .head(10) para ver somente as primeiras 10 linhas

ca_df = combustiveis_df[['Revenda', 'Municipio','Produto','Valor de Venda']]
display(ca_df)

#Exibe a 4a. linha.

display(ca_df.loc[3])

#Exibir da 10a. linha até a 20a.linha

display(ca_df.loc[9:19])

# Criar um dataframe gas_df contendo 
# apenas as 4 colunas (Revenda, Municipio, Produto, Valor de Venda)
# somente com combustível

gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display(gas_df)

display(gas_df['Valor de Venda'].max())

display(gas_df[['Revenda','Municipio','Valor de Venda']].max())