# -*- coding: utf-8 -*-
"""Aula 1 pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NLdadMa-wn42Hw9k6m5yibwv7QiOIQd4
"""

pip install pandas

import pandas as pd 

combustiveis_df = pd.read_csv("")