# -*- coding: utf-8 -*-
"""primeiro exemplo em Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yto0xL5Sk0uTe7_lBWhwxfoJefyGdSte
"""

import pandas as pd

combustiveis_df = pd.read_excel ("ca-2021-02.xlsx")

# Usa o print para ver o dataframe!
print(combustiveis_df)

display(combustiveis_df)

#Exibe as primeiras 5 linhas
display(combustiveis_df.head())

# Quero, na verdade, exibir as primeiras 15 linhas
display(combustiveis_df.head(15))

print(combustiveis_df.shape)

print(combustiveis_df.shape[0])

#Quais são as colunas e que tipo de dados cada um tem...

print(combustiveis_df.info())

print(combustiveis_df.describe())

display(combustiveis_df['Revenda'])

#add .head(10) para ver somente as primeiras 10 linhas

ca_df = combustiveis_df[['Revenda', 'Municipio','Produto','Valor de Venda']]
display(ca_df)

#Exibe a 4a. linha.

display(ca_df.loc[3])

#Exibir da 10a. linha até a 20a.linha

display(ca_df.loc[9:19])

# Criar um dataframe gas_df contendo 
# apenas as 4 colunas (Revenda, Municipio, Produto, Valor de Venda)
# somente com combustível

gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display(gas_df)

display(gas_df['Valor de Venda'].max())

display(gas_df[['Revenda','Municipio','Valor de Venda']].max())

#DataFrame.loc[] com múltiplas condições para filtragem
#Quais são os preços, postos que vendem ETANOL na minha cidade (INDAIATUBA) 
#ordenado do menor valor de venda para o maior
etanol_indaiatuba_df = ca_df.loc[(ca_df['Produto'] == 'ETANOL') & (ca_df['Municipio'] == 'INDAIATUBA')]
etanol_indaiatuba_df.sort_values(by='Valor de Venda')
display(etanol_indaiatuba_df)

# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & 
                            (combustiveis_df['Municipio'] == 'SAO PAULO') & 
                            ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), 
                            ['Valor de Venda']].mean())

# Como mostrar média de valor de venda POR COMBUSTÍVEL Brasil todo?
media_por_combustivel_df = ca_df[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)
display(media_por_combustivel_df)

#Quero adicionar uma coluna de valor booleano no combustiveis_df
# chamada "Ativo" que, por padrão, vai ser True para 
# TODAS as linhas
combustiveis_df['Ativo'] = True
print(combustiveis_df.info())
display(combustiveis_df.head())

# Exportar para Excel o dataframe com etanol em Indaiatuba....
etanol_indaiatuba_df.to_excel('etanol_indaiatuba.xlsx', sheet_name='Etanol em Indaiatuba')